# Generated by Django 4.1.7 on 2023-03-09 09:16

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="uploads/images/banners/", verbose_name="image"
                    ),
                ),
                (
                    "for_mobile",
                    models.BooleanField(
                        default=False,
                        help_text="If this image is used on mobile devices.",
                        verbose_name="Used in mobile devices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banner image",
                "verbose_name_plural": "Banner images",
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="uploads/images/categories/",
                        verbose_name="image",
                    ),
                ),
                (
                    "recommend",
                    models.BooleanField(
                        default=False,
                        help_text="If this category is recommended by the store owners",
                        verbose_name="recommend",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="customer",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=20, verbose_name="last name"),
                ),
                ("address", models.CharField(max_length=100, verbose_name="address")),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Landline/Cell phone number",
                        max_length=128,
                        region=None,
                        verbose_name="contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer profile",
                "verbose_name_plural": "Customer profiles",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="subtitle"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="description"),
                ),
                (
                    "recommend",
                    models.BooleanField(
                        default=False,
                        help_text="If this item is recommended by the store owners",
                        verbose_name="recommend",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="store.category", verbose_name="categories"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ItemVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=100, verbose_name="color")),
                ("rate", models.PositiveIntegerField(verbose_name="rate")),
                ("stock", models.PositiveIntegerField(verbose_name="stock")),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The item this item variant is linked with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="store.item",
                        verbose_name="item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item variant",
                "verbose_name_plural": "Item variants",
            },
        ),
        migrations.CreateModel(
            name="MerchantProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="merchant",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=20, verbose_name="last name"),
                ),
                (
                    "contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Landline/Cell phone number",
                        max_length=128,
                        region=None,
                        verbose_name="contact",
                    ),
                ),
                ("address", models.CharField(max_length=50, verbose_name="address")),
                (
                    "reason_for_signup",
                    models.CharField(
                        help_text="The reason for signup provided by user",
                        max_length=1000,
                        verbose_name="reason for signup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant profile",
                "verbose_name_plural": "Merchant profiles",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Date and time the order was placed",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Pending"), (1, "Delivered"), (2, "Cancelled")],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist",
                "verbose_name_plural": "Wishlist",
            },
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.itemvariant",
                        verbose_name="item variant",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        help_text="The wishlist this wishlist item is linked with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.wishlist",
                        verbose_name="wishlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist item",
                "verbose_name_plural": "Wishlist items",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(5)],
                        verbose_name="rating",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="store.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating",
                "verbose_name_plural": "Ratings",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "item_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="store.itemvariant",
                        verbose_name="item variant",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order this purchase is linked with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="store.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase",
                "verbose_name_plural": "Purchases",
            },
        ),
        migrations.CreateModel(
            name="ItemVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="uploads/images/items/",
                        verbose_name="image",
                    ),
                ),
                (
                    "item_variant",
                    models.ForeignKey(
                        help_text="The item variant this image is linked with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="store.itemvariant",
                        verbose_name="item variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item variant's image",
                "verbose_name_plural": "Item variant's images",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="The cart this cart item is linked with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.cart",
                        verbose_name="cart",
                    ),
                ),
                (
                    "item_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.itemvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart item",
                "verbose_name_plural": "Cart items",
            },
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("item", "user"), name="rating:item_user_constraint"
            ),
        ),
    ]
